name: Feature request
description: Suggest an idea
title: "[FEATURE] <title>"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you want.
